import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import ThemeRegistry from '../components/ThemeRegistry';
import Header from '../components/Header'; // Update import path
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeRegistry>
          <Providers>
            <Box
              sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}
            >
              <Header />
              <Container component="main" sx={{ mt: 4, mb: 4, flexGrow: 1 }}>
                {children}
              </Container>
            </Box>
          </Providers>
        </ThemeRegistry>
      </body>
    </html>
  );
}
